# Generated by Django 4.0.4 on 2022-06-01 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exile', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('number', models.CharField(max_length=17)),
                ('email', models.EmailField(max_length=254)),
                ('passport', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('rooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('rating', models.FloatField()),
                ('price', models.FloatField()),
                ('region', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=150)),
                ('id_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pictures', to='booking.pictures', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(auto_now_add=True)),
                ('date_end', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('amount_commission', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('id_realty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realty', to='booking.realty', verbose_name='Недвижимость')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='booking.user', verbose_name='Пользователь')),
            ],
        ),
    ]
