# Generated by Django 4.0.4 on 2022-06-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_options_alter_pictures_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pictures',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='realty',
            options={'verbose_name': 'Недвижимость', 'verbose_name_plural': 'Недвижимости'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.IntegerField(verbose_name='Цена без комиссии'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount_commission',
            field=models.IntegerField(verbose_name='Цена с комиссией'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_creation',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_end',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_start',
            field=models.DateField(auto_now_add=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='exile',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='bedrooms',
            field=models.IntegerField(verbose_name='Кол-во спален'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='rating',
            field=models.FloatField(verbose_name='Рэйтинг'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='region',
            field=models.CharField(max_length=250, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='rooms',
            field=models.IntegerField(verbose_name='Кол-во комнат'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='type',
            field=models.CharField(max_length=250, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=256, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=17, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.CharField(max_length=15, verbose_name='Паспортные данные'),
        ),
    ]
