# Generated by Django 4.0.4 on 2022-06-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_pictures_options_alter_realty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='rating',
            field=models.CharField(max_length=250, verbose_name='Рэйтинг'),
        ),
    ]
